name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  batty-matrix:
    strategy:
      matrix:
        include:
          - result: true
            alt: false
          - result: false
            alt: false
          - result: true
            alt: true
          - result: false
            alt: true
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - run: true || ${{ matrix.result }}
      - uses: './.github/actions/booly'
        with:
          skipit: ${{ matrix.alt }}
          greet: TAKE1
      - uses: './.github/actions/booly'
        with:
          greet: TAKE2
    runs-on: buildjet-4vcpu-ubuntu-2204
  did-it-work:
    needs: [ batty-matrix ]
    if: always()
    runs-on: buildjet-4vcpu-ubuntu-2204
    steps:
    - run: |-
        failures=$(echo '${{ toJSON(needs) }}' | jq -c '.[] | select (.result | IN("failure", "cancelled"))')
        test -z "${failures}"
